### PR TITLE
azure: fix Service Principal creation

### PR DESCRIPTION
**Pull request by nbusseneau**
Changes in #226 broke creation of a new Azure Service Principal when not providing an existing Service Principal for installing Cilium. This happens because Azure adds warnings for preview, deprecated and experimental commands, and incidentally there is one at the moment on the SP create command:

```console
$ az ad sp create-for-rbac --scopes /subscriptions/REDACTED --output json
In a future release, this command will NOT create a 'Contributor' role assignment by default. If needed, use the --role argument to explicitly create a role assignment.
Creating 'Contributor' role assignment under scope '/subscriptions/REDACTED'
The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
{
  "appId": "REDACTED",
  "displayName": "azure-cli-2021-06-15-16-57-00",
  "name": "http://azure-cli-2021-06-15-16-57-00",
  "password": "REDACTED",
  "tenant": "REDACTED"
}
```

This was not caught by the CI because it uses a fixed Service Principal (at least until we merge #308 😁 This is how I discovered the bug).

Re-add a wrapper function for `az` execs, forcing `az` output to be in JSON for unmarshalling purposes and suppressing warnings from preview, deprecated and experimental commands.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Comment by nbusseneau** [comment]
GKE hit a flow validation flake: https://github.com/cilium/cilium-cli/actions/runs/940142396
```
📋 Test Report
❌ 1/9 tests failed (1/81 actions), 0 warnings, 0 tests skipped, 0 scenarios skipped:
Test [allow-all]:
  ❌ allow-all/pod-to-local-nodeport/curl-1: cilium-test/client2-666976c95b-ckctn (10.4.0.83) -> cilium-test/echo-same-node (echo-same-node:8080)
```
Not sure if this a new one or one we've seen before.

**Comment by michi-covalent** [comment]
yeah i see a similar test failure in https://github.com/cilium/cilium-cli/pull/317/checks?check_run_id=2831962772#step:12:113 as well, although this one is from `no-policies`. `curl` is failing for some reason.

**Review by tklauser — APPROVED** [review]
Thanks!

**Review by ti-mo — APPROVED** [review]
Thanks! Ignore the connectivity failure for now.

**Comment by michi-covalent** [comment]
we are tracking flow validation flakes in https://github.com/cilium/cilium-cli/pull/319. merging

**Pull request merged**
