### PR TITLE
Improve the helm values autodetection logic

### PR DESCRIPTION
**Pull request by giorio94**
Please review commit by commit, and refer to the individual messages for additional details.

* Remove unused fields/parameters from the `getHelmValues` logic;
* Drop support for EOL Cilium v1.11 and earlier in helm values generation;  
* Drop broken `bpf.masquerade` autodetection logic;
* Fix retrieval of the user-configured routing mode, and uniform retrieval of nested helm value;
* Improve KPR autodetection logic to not override user configuration, and not configure deprecated values;
* Fix KPR probing in connectivity tests to account for both legacy and current values.
* Replace the remaining references to deprecated KPR settings in GHA workflows.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Comment by giorio94** [comment]
The failure appears to be legitimate, as it uncovered an already existing bug causing incorrect KPR features detection when configured using the new format (i.e., true|false). Converting back to draft while addressing it.

**Comment by giorio94** [comment]
I've pushed a commit to address the KPR feature detection issue. Back to reviewable state.

**Review by brlbil — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Nice cleanup!

**Review by michi-covalent — APPROVED** [review]
i didn't know about `unstructured.NestedString`. very cool 🥰

**Review by sayboras — APPROVED** [review]
Thanks :heavy_check_mark:

**Review by tommyp1ckles — APPROVED** [review]

**Comment by michi-covalent** [comment]
6 approvals. good enough for me.

**Pull request merged**
