### PR TITLE
Bump Cilium version to 1.10.2, Hubble to v0.8.0

### PR DESCRIPTION
**Pull request by tklauser**
See individual commits.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Comment by tklauser** [comment]
The new [EKS (ENI)](https://github.com/cilium/cilium-cli/pull/358/checks?check_run_id=2893134552) failure is #355.

**Comment by tklauser** [comment]
The [External Workloads failure](https://github.com/cilium/cilium-cli/pull/358/checks?check_run_id=2893134575) looks like a real issue with 1.10. It looks like the Cilium endpoints in the cluster are unreachable for Cilium agent running in the VM.

```
 Cluster health:                                                                        1/3 reachable   (2021-06-23T09:00:33Z)
  Name                                                                                 IP              Node        Endpoints
  cilium-cilium-cli-963673456-vm/gke-cilium-cilium-cli-96-default-pool-138a09de-66px   10.168.0.97     reachable   unreachable
  cilium-cilium-cli-963673456-vm/gke-cilium-cilium-cli-96-default-pool-138a09de-n7d7   10.168.0.98     reachable   unreachable
```

I'm trying to replicate this on my own GKE cluster.

/cc @jrajahalme for visibility

**Comment by jrajahalme** [comment]
> The [External Workloads failure](https://github.com/cilium/cilium-cli/pull/358/checks?check_run_id=2893134575) looks like a real issue with 1.10. It looks like the Cilium endpoints in the cluster are unreachable for Cilium agent running in the VM.
> 
> ```
>  Cluster health:                                                                        1/3 reachable   (2021-06-23T09:00:33Z)
>   Name                                                                                 IP              Node        Endpoints
>   cilium-cilium-cli-963673456-vm/gke-cilium-cilium-cli-96-default-pool-138a09de-66px   10.168.0.97     reachable   unreachable
>   cilium-cilium-cli-963673456-vm/gke-cilium-cilium-cli-96-default-pool-138a09de-n7d7   10.168.0.98     reachable   unreachable
> ```

Most likely a red herring, as the VM has successfully connected to the  etcd container in the `clustermesh-apiserver` pod. So  basically datapath is working, it looks like. This has to be more specific to the DNS service?

**Comment by jrajahalme** [comment]
Looked into the external workloads fail. It works if the VM in installed with Cilium 1.9.8. With Cilium 1.10.1 in the VM no services are returned by `cilium service list` in the VM. Comparing Cilium agent logs in the VM between these versions I see this common part:
```
level=debug msg="Added new service frontend:10.35.240.10/ports=[dns-tcp dns]/selector=map[k8s-app:kube-dns]" serviceName=jarno-test/kube-system/kube-dns subsys=k8s
level=debug msg="Updating backends to map[10.32.0.168:map[dns:0xc0003ed840 dns-tcp:0xc0003ed880] 10.32.1.20:map[dns:0xc0003ed900 dns-tcp:0xc0003ed960]]" serviceName=jarno-test/kube-system/kube-dns subsys=k8s
level=debug msg="Kubernetes service definition changed" action=service-updated endpoints="10.32.0.168:53/TCP,10.32.0.168:53/UDP,10.32.1.20:53/TCP,10.32.1.20:53/UDP" k8sNamespace=kube-system k8sSvcName=kube-dns old-service=nil service="frontend:10.35.240.10/ports=[dns-tcp dns]/selector=map[k8s-app:kube-dns]" subsys=k8s-watcher
```
But the following only appears (after the line above) on Cilium 1.9.8:
```
level=debug msg="Upserting service" backends="[{0  {10.32.0.168 {TCP 53} 0}} {0  {10.32.1.20 {TCP 53} 0}}]" loadBalancerSourceRanges="[]" serviceIP="{10.35.240.10 {TCP 53} 0}" serviceName=kube-dns serviceNamespace=kube-system sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=ClusterIP
level=debug msg="Acquired service ID" backends="[{0  {10.32.0.168 {TCP 53} 0}} {0  {10.32.1.20 {TCP 53} 0}}]" loadBalancerSourceRanges="[]" serviceID=4 serviceIP="{10.35.240.10 {TCP 53} 0}" serviceName=kube-dns serviceNamespace=kube-system sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=ClusterIP
level=debug msg="Adding new backend" backendID=4 backends="[{0  {10.32.0.168 {TCP 53} 0}} {0  {10.32.1.20 {TCP 53} 0}}]" l3n4Addr="{10.32.0.168 {TCP 53} 0}" loadBalancerSourceRanges="[]" serviceID=4 serviceIP="{10.35.240.10 {TCP 53} 0}" serviceName=kube-dns serviceNamespace=kube-system sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=ClusterIP
level=debug msg="Adding new backend" backendID=5 backends="[{0  {10.32.0.168 {TCP 53} 0}} {0  {10.32.1.20 {TCP 53} 0}}]" l3n4Addr="{10.32.1.20 {TCP 53} 0}" loadBalancerSourceRanges="[]" serviceID=4 serviceIP="{10.35.240.10 {TCP 53} 0}" serviceName=kube-dns serviceNamespace=kube-system sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Cluster svcType=ClusterIP
```

So something has changed in Cilium 1.10.1 to cause the service backends not being populated when running as a VM.

**Comment by jrajahalme** [comment]
The first missing log line `"Upserting service"` is unconditionally logged by `service.UpsertService()`, which is called by `watchers.addK8sSVCs()`, which is called for `UpdateService` event type unconditionally right after the `"Kubernetes service definition changed"` log. Assuming the event type is consistent between v1.9.8 and v.1.10.1, it must be that `watchers.addK8sSVCs()` is not calling `service.UpsertService()` in this case.

**Comment by jrajahalme** [comment]
Fails the same way with Cilium v1.10.0 & v1.10.1.

**Comment by jrajahalme** [comment]
Fix in https://github.com/cilium/cilium/pull/16662

**Comment by tklauser** [comment]
Converting to draft until cilium/cilium#16662 is merged, backported and shows up in the next 1.10.x release.

**Comment by tklauser** [comment]
Rebased and updated to Cilium 1.10.2 which should fix the external workloads failure.

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
