### PR TITLE
rename the configuration file to the right name

### PR DESCRIPTION
**Pull request by aanm**
MLH uses cilium-actions.yml as its configuration file. Should then be
named accordingly.

Fixes: 5b8a8405425b (".github: Add maintainer's little helper integration")
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by pchaigno — CHANGES_REQUESTED** [review]
Couldn't we change maintainer's little helper instead? `cilium-action.yaml` as a name for a file under `.github/workflows` is really not helping tell what it's about :smile: 

I'm happy to send the PRs to cilium/cilium and maintainer's little helper if that's all that's needed.

**Comment by aanm** [comment]
> Couldn't we change maintainer's little helper instead? `cilium-action.yaml` as a name for a file under `.github/workflows` is really not helping tell what it's about 
> 
> I'm happy to send the PRs to cilium/cilium and maintainer's little helper if that's all that's needed.

That includes all stable branches in cilium/cilium as well as in hubble.

**Comment by pchaigno** [comment]
> > I'm happy to send the PRs to cilium/cilium and maintainer's little helper if that's all that's needed.
> 
> That includes all stable branches in cilium/cilium as well as in hubble.

That's totally fine to me. I can send as many PRs as required :-)

**Comment by pchaigno** [comment]
PRs opened:
- https://github.com/cilium/cilium/pull/16455
- https://github.com/cilium/cilium/pull/16456
- https://github.com/cilium/cilium/pull/16457
- https://github.com/cilium/cilium/pull/16458
- https://github.com/cilium/hubble/pull/569

**Comment by aanm** [comment]
Closed by https://github.com/cilium/github-actions/pull/15

**Pull request closed without merging**
