### PR TITLE
Prepare for release v0.8.2

### PR DESCRIPTION
**Pull request by michi-covalent**

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by glibsm** [comment]
The PR as a whole is confusing, but the individual commits make sense. I assume you plan to branch release from eb28eedda5b16d5f4e03ef47cfebeadcf333a20f?

**Comment by michi-covalent** [comment]
@glibsm not branching but tag `v0.8.2` from eb28eed. so far we've been releasing from master branch.

previous release PR as a reference https://github.com/cilium/cilium-cli/pull/343

**Comment by michi-covalent** [comment]
i will document the current release process in a separate PR.

**Comment by glibsm** [comment]
> i will document the current release process in a separate PR.

That would be great.

**Comment by tklauser** [comment]
> i will document the current release process in a separate PR.

Also see #363

**Pull request merged**
