### PR TITLE
CI workflows: Build cilium binary

### PR DESCRIPTION
**Pull request by michi-covalent**
We need the binary for the sysdump command in case of failure.

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
* External workloads failed with:

```
 ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
 - The resource 'projects/***/zones/us-west2-a/instances/cilium-cilium-cli-1023755226-vm' was not found
```

https://github.com/cilium/cilium-cli/actions/runs/1023755226

* AKS failed due to missing privileges, likely because AKS secrets were changed at around the same time? /cc @nbusseneau 

https://github.com/cilium/cilium-cli/actions/runs/1023755252

Merging this PR despite the above failures as we currently don't get sysdumps for some failed tests without building the `cilium` binary.

**Review by nbusseneau — CHANGES_REQUESTED** [review]
Sorry but I have to veto that PR :/

The whole point of having the PR-built `cilium` run in-cluster is to forbid attackers to edit `cilium-cli` code and then submit PR and execute `cilium` in the context of the workflow, which would allow them to leak our secrets due to the `pull_request_target` triggers running in a privileged context. This is why these were removed in #212.

We cannot have the workflows themselves use code coming from the PR.

**Comment by nbusseneau** [comment]
> 
> 
>     * External workloads failed with:
> 
> 
> ```
>  ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
>  - The resource 'projects/***/zones/us-west2-a/instances/cilium-cilium-cli-1023755226-vm' was not found
> ```
> 
> https://github.com/cilium/cilium-cli/actions/runs/1023755226
> 
>     * AKS failed due to missing privileges, likely because AKS secrets were changed at around the same time? /cc @nbusseneau
> 
> 
> https://github.com/cilium/cilium-cli/actions/runs/1023755252
> 
> Merging this PR despite the above failures as we currently don't get sysdumps for some failed tests without building the `cilium` binary.

Unrelated to my comment above: in this instance I would advocate for re-running the workflows:
- The GCP VM boot issue is a known infrastructure issue, and is one of the cases where re-running is allowed (and should actually be automated, it's just not done yet, in case anyone's up for it :D).
- Likewise, I would also consider the AKS failure due to missing privileges to be infrastructure issue, hence re-running.

**Comment by tklauser** [comment]
Superseded by #423

**Pull request closed without merging**
