### PR TITLE
Prevent unmanaged pods in GKE's containerd flavors (cilium/cilium#18486)

### PR DESCRIPTION
**Pull request by bmcustodio**
Porting https://github.com/cilium/cilium/pull/18486 to the CLI.

### CODE REVIEW

**Review by ldelossa — CHANGES_REQUESTED** [review]
@bmcustodio 

After the CNI is installed, we expect any taints to be removed from nodes correct? I do not see any updates where we update the *removal* of the tain to now remove "NoExecute" taint. 

Am I missing something?

**Comment by bmcustodio** [comment]
> I do not see any updates where we update the removal of the taint to now remove "NoExecute" taint.

@ldelossa I am not sure if I got the question right, but [Cilium does remove the taint regardless of its effect](https://github.com/cilium/cilium/blob/master/pkg/k8s/node.go#L251-L288).

**Comment by bmcustodio** [comment]
It's also probably pointing out that this is just a port of a piece of code that has been [reviewed](https://github.com/cilium/cilium/pull/18486) upstream.

**Comment by ldelossa** [comment]
@bmcustodio gotchya, I was assuming the taint being removed was hard coded, and we needed to update it.

**Review by christarazi — APPROVED** [review]

**Review by christarazi — COMMENTED** [review]
What is the second commit msg referencing by saying?

```
[ upstream commit b049574 ]
```

**Comment by bmcustodio** [comment]
@christarazi whenever I (back-)port something, I usually always include a reference to the original commit. In this case, it's just a reference to the original `c/c` commit, but it has no other meaning or isn't used by any tooling that I am aware of.

**Comment by christarazi** [comment]
@bmcustodio That makes sense to me, but it's not clear where that commit SHA is coming from, so I'd suggest either linking it as a GH link or mentioning it's a cilium/cilium commit.

**Comment by bmcustodio** [comment]
@christarazi sure, makes sense! I've rebased the PR and replaced the "upstream" mentions with "cilium/cilium" ones.

**Review by tklauser — APPROVED** [review]

**Pull request merged**
