### PR TITLE
Improve connectivity check flow validation

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #52

### CODE REVIEW

**Comment by jrajahalme** [comment]
Rebased this locally like so:

1st commit:
```
connectivity/tests/host.go
< -				{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.ICMP(8)), Expect: true, Msg: "ICMP request"},
< -				{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.ICMP(0)), Expect: true, Msg: "ICMP response"},
...
< +				First: filters.FlowRequirement{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.ICMP(8)), Msg: "ICMP request"},
< +				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.ICMP(0)), Msg: "ICMP response"},
---
> -				{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.Or(filters.ICMP(8), filters.ICMPv6(128))), Expect: true, Msg: "ICMP request"},
> -				{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.Or(filters.ICMP(0), filters.ICMPv6(129))), Expect: true, Msg: "ICMP response"},
...
> +				First: filters.FlowRequirement{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.Or(filters.ICMP(8), filters.ICMPv6(128))), Msg: "ICMP request"},
> +				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.Or(filters.ICMP(0), filters.ICMPv6(129))), Msg: "ICMP response"},

connectivity/tests/pod.go:
> -			destination := net.JoinHostPort(echo.Pod.Status.PodIP, strconv.Itoa(8080))

<  
< -			_, err := client.K8sClient.ExecInPod(ctx, client.Pod.Namespace, client.Pod.Name, check.ClientDeploymentName, curlCommand(echo.Pod.Status.PodIP+":8080"))
< +			cmd := curlCommand(echo.Pod.Status.PodIP + ":8080")
---
> -
> -			_, err := client.K8sClient.ExecInPod(ctx, client.Pod.Namespace, client.Pod.Name, check.ClientDeploymentName, curlCommand(destination))
> +			cmd := curlCommand(net.JoinHostPort(echo.Pod.Status.PodIP, strconv.Itoa(8080)))
```

4th commit:
```
connectivity/tests/host.go:
<  				First: filters.FlowRequirement{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.ICMP(8)), Msg: "ICMP request"},
< -				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.ICMP(0)), Msg: "ICMP response"},
< +				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.ICMP(0)), Msg: "ICMP response", SkipOnAggregation: true},
---
>  				First: filters.FlowRequirement{Filter: filters.And(filters.IP(client.Pod.Status.PodIP, hostIP), filters.Or(filters.ICMP(8), filters.ICMPv6(128))), Msg: "ICMP request"},
> -				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.Or(filters.ICMP(0), filters.ICMPv6(129))), Msg: "ICMP response"},
> +				Last:  filters.FlowRequirement{Filter: filters.And(filters.IP(hostIP, client.Pod.Status.PodIP), filters.Or(filters.ICMP(0), filters.ICMPv6(129))), Msg: "ICMP response", SkipOnAggregation: true},
```

@tgraf Can push this here if OK by you :-)

**Comment by jrajahalme** [comment]
After fixing conflicts I get various kinds of errors in flow validation:
```
ℹ️  Monitor aggregation detected, will skip some flow validation steps
⌛ [kind-kind] Waiting for deployments [client echo-same-node] to become ready...
⌛ [kind-kind] Waiting for deployments [echo-other-node] to become ready...
⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client-68c6675687-27jpg to appear...
⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-588bf78fbb-f4v9v to appear...
⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-779c8c89d6-hpf79 to appear...
⌛ [kind-kind] Waiting for service echo-other-node to become ready...
⌛ [kind-kind] Waiting for service echo-same-node to become ready...
🔭 Enabling Hubble telescope...
Handling connection for 4245
ℹ️  Hubble is OK, flows: 8192/8192

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-pod] Testing cilium-test/client-68c6675687-27jpg -> cilium-test/echo-other-node-588bf78fbb-f4v9v...
---------------------------------------------------------------------------------------------------------------------
✅ curl command ["curl" "--silent" "--fail" "--show-error" "--connect-timeout" "5" "--output" "/dev/null" "10.244.0.18:8080"] succeeded
❌ Unable to retrieve flows of pod "cilium-test/client-68c6675687-27jpg": timeout while waiting for condition, last error: no flows returned
❌ Flow validation failed for pod cilium-test/echo-other-node-588bf78fbb-f4v9v: 2 failures (first: 0, last: 0, matched: 0, nlog: 2)
❌ SYN and(ip(src=10.244.1.196,dst=10.244.0.18),tcp(dstPort=8080),tcpflags(syn)) not found for pod cilium-test/echo-other-node-588bf78fbb-f4v9v
❌ FIN and(ip(src=10.244.1.196,dst=10.244.0.18),tcp(dstPort=8080),tcpflags(ack,fin)) not found for pod cilium-test/echo-other-node-588bf78fbb-f4v9v
📄 Flow logs of pod cilium-test/echo-other-node-588bf78fbb-f4v9v:
❓Apr  7 21:32:33.611: 10.244.0.235:40200 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: SYN)
❓Apr  7 21:32:33.611: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40200 to-stack FORWARDED (TCP Flags: SYN, ACK)
❓Apr  7 21:32:33.611: 10.244.0.235:40200 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:33.613: 10.244.0.235:40200 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:33.617: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40200 to-stack FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:33.617: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40200 to-stack FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:33.617: 10.244.0.235:40200 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:33.617: 10.244.0.235:40200 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:34.611: 10.244.0.235:40210 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: SYN)
❓Apr  7 21:32:34.611: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40210 to-stack FORWARDED (TCP Flags: SYN, ACK)
❓Apr  7 21:32:34.611: 10.244.0.235:40210 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:34.611: 10.244.0.235:40210 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:34.621: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40210 to-stack FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:34.624: 10.244.0.235:40210 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:34.624: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40210 to-stack FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:34.624: 10.244.0.235:40210 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:35.611: 10.244.0.235:40220 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: SYN)
❓Apr  7 21:32:35.611: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40220 to-stack FORWARDED (TCP Flags: SYN, ACK)
❓Apr  7 21:32:35.611: 10.244.0.235:40220 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:35.612: 10.244.0.235:40220 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:35.615: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40220 to-stack FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:35.617: 10.244.0.235:40220 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:35.617: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40220 to-stack FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:35.618: 10.244.0.235:40220 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:36.611: 10.244.0.235:40232 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: SYN)
❓Apr  7 21:32:36.611: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40232 to-stack FORWARDED (TCP Flags: SYN, ACK)
❓Apr  7 21:32:36.611: 10.244.0.235:40232 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:36.612: 10.244.0.235:40232 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:36.615: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40232 to-stack FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:36.617: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40232 to-stack FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:36.617: 10.244.0.235:40232 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:36.617: 10.244.0.235:40232 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:37.611: 10.244.0.235:40248 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: SYN)
❓Apr  7 21:32:37.611: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40248 to-stack FORWARDED (TCP Flags: SYN, ACK)
❓Apr  7 21:32:37.611: 10.244.0.235:40248 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr  7 21:32:37.611: 10.244.0.235:40248 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:37.616: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40248 to-stack FORWARDED (TCP Flags: ACK, PSH)
❓Apr  7 21:32:37.619: 10.244.0.235:40248 -> cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
❓Apr  7 21:32:37.621: cilium-test/echo-other-node-588bf78fbb-f4v9v:8080 -> 10.244.0.235:40248 to-stack FORWARDED (TCP Flags: ACK, FIN)
❌ [pod-to-pod] cilium-test/client-68c6675687-27jpg (10.244.1.196) -> cilium-test/echo-other-node-588bf78fbb-f4v9v (10.244.0.18)
```
There seems to be a mismatch between the expected client pod IP (10.244.1.196) and the observed one (10.244.0.235). `kubectl get pods` shows:
```
$ kubectl get pods --all-namespaces -o wide
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE     IP             NODE                 NOMINATED NODE   READINESS GATES
cilium-test          client-68c6675687-27jpg                      1/1     Running   0          2m30s   10.244.1.196   kind-worker          <none>           <none>
cilium-test          echo-other-node-588bf78fbb-f4v9v             1/1     Running   0          2m30s   10.244.0.18    kind-control-plane   <none>           <none>
cilium-test          echo-same-node-779c8c89d6-hpf79              1/1     Running   0          2m30s   10.244.1.194   kind-worker          <none>           <none>
kube-system          cilium-7lb6m                                 1/1     Running   0          13m     172.18.0.2     kind-worker          <none>           <none>
kube-system          cilium-operator-5f54d69cb8-bdbhc             1/1     Running   0          14m     172.18.0.2     kind-worker          <none>           <none>
kube-system          cilium-rkm4v                                 1/1     Running   0          13m     172.18.0.3     kind-control-plane   <none>           <none>
kube-system          coredns-f9fd979d6-fxls4                      1/1     Running   0          17m     10.244.0.121   kind-control-plane   <none>           <none>
kube-system          coredns-f9fd979d6-kdx9k                      1/1     Running   0          17m     10.244.1.221   kind-worker          <none>           <none>
kube-system          etcd-kind-control-plane                      1/1     Running   0          18m     172.18.0.3     kind-control-plane   <none>           <none>
kube-system          hubble-relay-775bdffbc-jnzwt                 1/1     Running   0          13m     10.244.1.17    kind-worker          <none>           <none>
kube-system          kube-apiserver-kind-control-plane            1/1     Running   0          18m     172.18.0.3     kind-control-plane   <none>           <none>
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   0          18m     172.18.0.3     kind-control-plane   <none>           <none>
kube-system          kube-proxy-drkvp                             1/1     Running   0          17m     172.18.0.3     kind-control-plane   <none>           <none>
kube-system          kube-proxy-qm2nn                             1/1     Running   0          17m     172.18.0.2     kind-worker          <none>           <none>
kube-system          kube-scheduler-kind-control-plane            1/1     Running   0          18m     172.18.0.3     kind-control-plane   <none>           <none>
local-path-storage   local-path-provisioner-78776bfc44-69c6w      1/1     Running   0          17m     10.244.1.78    kind-worker          <none>           <none>
```

I have no idea where the observed source address 10.244.0.235 comes from. CEP for `cilium-test/client-68c6675687-27jpg`:
```
...
status:
  encryption: {}
  external-identifiers:
    container-id: 936a551eac0217c592c23ad15446547a5eb972802e5a55dc801f925752b9e61b
    k8s-namespace: cilium-test
    k8s-pod-name: client-68c6675687-27jpg
    pod-name: cilium-test/client-68c6675687-27jpg
  id: 44
  identity:
    id: 17625
    labels:
    - k8s:io.cilium.k8s.policy.cluster=kind-kind
    - k8s:io.cilium.k8s.policy.serviceaccount=default
    - k8s:io.kubernetes.pod.namespace=cilium-test
    - k8s:kind=client
    - k8s:name=client
  networking:
    addressing:
    - ipv4: 10.244.1.196
    node: 172.18.0.2
  state: ready
```

**Comment by jrajahalme** [comment]
Correction, the observed source address 10.244.0.235 is the `cilium_host` address on the "other" node, in my case the kind control plane node. Somehow the connection seems to be coming from the "other" node, and no flows are received from the node where the client is supposed to be running at.

**Comment by jrajahalme** [comment]
It's almost as if `ExecInPod()` would execute the `curl` command in wrong node?

**Comment by jrajahalme** [comment]
The above seems to be an artifact of Kind, as I could not replicate it in GKE, which consistently succeeds `cilium connectivity test`, both with the default GKE datapath mode, as well as with `tunnel=vxlan`.

With kind we are running two `cilium_host` devices, one for each node. Presumably they are in the same root namespace and somehow get randomly(?) selected as a source address, even for packets between pods in the same node?

**Comment by jrajahalme** [comment]
Turns out the `cilium_host` flows are pod readiness probes, and the test client flows were missed because of a 100ms offset in the flow start time. I had to remove this offset to make this work with a Kind cluster:
```
commit 13460562e7df735960bba8bb61c1e9f28903f440
Author: Jarno Rajahalme <jarno@covalent.io>
Date:   Thu Apr 8 11:40:55 2021 -0700

    tests: Validate flows from the beginning of the test run
    
    Flows were skipped over in validation with the 100ms offset when
    testing with a Kind cluster. Remove the start time offset to fix this.
    
    Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
---
 connectivity/check/check.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/connectivity/check/check.go b/connectivity/check/check.go
index b1c7e5f..f91c571 100644
--- a/connectivity/check/check.go
+++ b/connectivity/check/check.go
@@ -488,7 +488,7 @@ func (t *TestRun) ValidateFlows(ctx context.Context, pod, podIP string, req filt
 	defer w.Cancel()
 
 retry:
-	flows, err := t.getFlows(ctx, hubbleClient, t.started.Add(100*time.Millisecond), pod, podIP)
+	flows, err := t.getFlows(ctx, hubbleClient, t.started, pod, podIP)
 	if err != nil || flows == nil || len(flows.flows) == 0 {
 		if err == nil {
 			err = fmt.Errorf("no flows returned")
```

@tgraf Do you recall the reasoning for the 100ms offset here?

**Comment by tgraf** [comment]
@jrajahalme Is it correct that you have inherited these changes and merged them via the policy tests?

**Comment by tgraf** [comment]
Merged in via #158

**Pull request closed without merging**
