### PR TITLE
Connectivity tests counter.

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
Connectivity tests counter added to make it more user friendly.

### CODE REVIEW

**Review by tklauser — COMMENTED** [review]
Should we report test counter when skipping a test as well? i.e. in the `t.Context().skip` and `t.skip` calls?

**Comment by viktor-kurchenko** [comment]
> Should we report test counter when skipping a test as well? i.e. in the `t.Context().skip` and `t.skip` calls?

I thought about it and I didn't do that because skip action doesn't consume time (happens immediately).
However from a consistency point of view maybe it's better to add a counter.

**Comment by tklauser** [comment]
> > Should we report test counter when skipping a test as well? i.e. in the `t.Context().skip` and `t.skip` calls?
> 
> I thought about it and I didn't do that because skip action doesn't consume time (happens immediately). However from a consistency point of view maybe it's better to add a counter.

Yeah, I think it would be better for consistency.

**Comment by viktor-kurchenko** [comment]
> > > Should we report test counter when skipping a test as well? i.e. in the `t.Context().skip` and `t.skip` calls?
> > 
> > 
> > I thought about it and I didn't do that because skip action doesn't consume time (happens immediately). However from a consistency point of view maybe it's better to add a counter.
> 
> Yeah, I think it would be better for consistency.

Done.

**Review by tklauser — APPROVED** [review]
Thanks

**Review by nebril — APPROVED** [review]

**Pull request merged**
