### PR TITLE
chore(sysdump): reduce sysdump warnings and unify output

### PR DESCRIPTION
**Pull request by f1ko**
Signed-off-by: Filip Nikolic

Fixes https://github.com/cilium/cilium-cli/issues/1083

### CODE REVIEW

**Comment by F1ko** [comment]
@ldelossa could it be that it is a flaky test? I cannot explain as to how my changes would impact a no-policy pod-to-service connectivity test.

**Review by tklauser — CHANGES_REQUESTED** [review]
Thanks for the PR @F1ko.

It looks like the change is a mix of convenience refactoring and the actual fix for reducing the warnings. Could you please split up the change into individual commits, i.e. commits dedicated to refactoring and then the actual commit to reduce the warnings on top of that? That way it will be easier to review the change. Thanks

**Comment by nbusseneau** [comment]
@F1ko I think there might have been a mistake during the rebase, as there are merge and revert commits in the log. Would it be possible to clean up the history? I can give pointers if you need help with git handling.

Also, as MLH is suggesting, you need to sign-off all commits. I see you have done so, but the format is incorrect: you need the name and address mail in there, as pointed in the docs: `Signed-off-by: Random J Developer <random@developer.example.org>`

**Comment by F1ko** [comment]
Apologies for the delay.

Now everything should be as requested.

**Comment by nbusseneau** [comment]
I am auto-acking on behalf of `github-sec` and `ci-structure`, since the changes don't require reviews from these team anymore (was only necessary due to the merge commits, now gone).

**Review by nbusseneau — APPROVED** [review]

**Comment by joestringer** [comment]
@f1ko / @tklauser is this PR still being actively developed? It seems to be a bit stale and at least needs a rebase.

**Comment by f1ko** [comment]
It is indeed stale @joestringer .

Will close it for now and open a new one incorporating the feedback when I get to it.

**Pull request closed without merging**
