### PR TITLE
ci: fix AKS testing on `v0.10`

### PR DESCRIPTION
**Pull request by nbusseneau**
See per commit.

### CODE REVIEW

**Comment by tklauser** [comment]
AKS workflow is still failing: https://github.com/cilium/cilium-cli/runs/7653973946?check_suite_focus=true

I assume we'd need to test this by uncommenting https://github.com/cilium/cilium-cli/blob/13ff24d23a0fdd2eaad907de210252822ed45424/.github/workflows/aks.yaml#L17 in a test commit?

**Comment by nbusseneau** [comment]
Yes we can test, I was lazy and did not do it because it already works in `master` 🙈

**Comment by nbusseneau** [comment]
Here we go: https://github.com/cilium/cilium-cli/actions/runs/2790250882

**Comment by nbusseneau** [comment]
Login passed in test run: https://github.com/cilium/cilium-cli/actions/runs/2790262176

**Comment by nbusseneau** [comment]
@tklauser Testing was a good idea, because we also forgot to backport this: e36f3ad0c98bcdda82b55de52e83dd582a336d4e
where we remove the taint system from the set up.

**Review by sayboras — APPROVED** [review]

**Comment by tklauser** [comment]
AKS workflow passed with test commit 🎉 https://github.com/cilium/cilium-cli/runs/7699030050?check_suite_focus=true

**Review by tklauser — APPROVED** [review]

**Pull request merged**
