### PR TITLE
Remove the repo lock workflow

### PR DESCRIPTION
**Pull request by michi-covalent**
https://github.com/cilium/cilium/pull/34178 got merged. vendor cilium-cli from cilium/cilium repo.

4 commits:

- pick up the latest cilium code from main branch: https://github.com/cilium/cilium/commit/e528f991156301a04be66d69e379e699b803d27d
- update main.go to import the CLI from cilium/cilium repo.
- delete unused code.
- unlock the repo and update CONTRIBUTING.md.

### CODE REVIEW

**Comment by viktor-kurchenko** [comment]
@michi-covalent was the intention of this PR?
I thought we would archive the repo after merging CLI in the cilium repo.

**Comment by michi-covalent** [comment]
>  I thought we would archive the repo after merging CLI in the cilium repo.

no we are keeping cilium-cli repo. see https://github.com/cilium/design-cfps/blob/main/cilium/CFP-25694-move-cilium-cli-to-cilium-repo.md?plain=1#L77-L90

**Review by viktor-kurchenko — APPROVED** [review]
Looks innocent)

**Review by sayboras — APPROVED** [review]
Seems legit :heavy_check_mark:

**Review by marseel — APPROVED** [review]

**Review by asauber — APPROVED** [review]

**Comment by NordMike** [comment]
Is the actual source code of cilium CLI in another repo now? It would be nice to have this mentioned in README.

**Comment by michi-covalent** [comment]
yes it's in cilium/cilium repo. it's documented in CONTRIBUTING.md: https://github.com/cilium/cilium-cli/blob/main/CONTRIBUTING.md#contribution-workflow

**Pull request merged**
