### PR TITLE
Dump raw flows on debug

### PR DESCRIPTION
**Pull request by michi-covalent**
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
sample output
```
  RAW_FLOW: pod-to-world/http-to-one-one-one-one-1 {"flow":{"time":"2021-09-14T15:52:27.728174176Z","verdict":"FORWARDED","ethernet":{"source":"5e:25:50:b2:72:48","destination":"66:bc:66:25:2a:81"},"IP":{"source":"10.0.0.253","destination":"1.1.1.1","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":43090,"destination_port":80,"flags":{"ACK":true}}},"source":{"ID":3003,"identity":7611,"namespace":"cilium-test","labels":["k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test","k8s:io.cilium.k8s.policy.cluster=minikube","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=cilium-test","k8s:kind=client","k8s:name=client2","k8s:other=client"],"pod_name":"client2-5998d566b4-psvdq"},"destination":{"identity":16777218,"labels":["cidr:1.1.1.1/32","reserved:world"]},"Type":"L3_L4","node_name":"minikube","destination_names":["one.one.one.one"],"event_type":{"type":4,"sub_type":3},"traffic_direction":"EGRESS","trace_observation_point":"TO_STACK","is_reply":false,"Summary":"TCP Flags: ACK"}}
```

**Comment by michi-covalent** [comment]
yeah for now it's only guarded by the --debug flag, but we can also check for the --all-flows flag as well. we set both of these flags in the CI workflows anyways.

**Comment by michi-covalent** [comment]
... and only dump raw flows on failed tests.

**Comment by michi-covalent** [comment]
it doesn't fail when i want it to 😐 re-triggering.

**Comment by ldelossa** [comment]
@michi-covalent sounds good, also do we want to get these raw flows into a log file for sysdump collection or not in this pr?

**Pull request closed without merging**
