### PR TITLE
sysdump: Use intermediate import package for supported envoy resources

### PR DESCRIPTION
**Pull request by sayboras**
This is to avoid the similar happening again in the future, when we add more envoy resource types.

Relates: https://github.com/cilium/cilium-cli/pull/1756
Relates: https://github.com/cilium/cilium/pull/26469

### CODE REVIEW

**Review by rolinh — CHANGES_REQUESTED** [review]
I think there's now a new replace directive in v1.14.0-rc.0:
```
replace (
	github.com/miekg/dns => github.com/cilium/dns v1.1.51-0.20220729113855-5b94b11b46fc
	go.universe.tf/metallb => github.com/cilium/metallb v0.1.1-0.20220829170633-5d7dfb1129f7
	k8s.io/client-go => github.com/cilium/client-go v0.27.2-fix
	sigs.k8s.io/controller-tools => github.com/cilium/controller-tools v0.6.2
)
```

**Comment by sayboras** [comment]
> I think there's now a new replace directive in v1.14.0-rc.0:
> 
> ```
> replace (
> 	github.com/miekg/dns => github.com/cilium/dns v1.1.51-0.20220729113855-5b94b11b46fc
> 	go.universe.tf/metallb => github.com/cilium/metallb v0.1.1-0.20220829170633-5d7dfb1129f7
> 	k8s.io/client-go => github.com/cilium/client-go v0.27.2-fix
> 	sigs.k8s.io/controller-tools => github.com/cilium/controller-tools v0.6.2
> )
> ```

Good catch, thanks :100:

**Review by rolinh — APPROVED** [review]
lgtm

**Review by tklauser — CHANGES_REQUESTED** [review]
Please split the go.mod update into a separate commit.

**Review by tklauser — APPROVED** [review]

**Pull request merged**
