### PR TITLE
workflows: remove test exception from EKS

### PR DESCRIPTION
**Pull request by nbusseneau**
This was a leftover from https://github.com/cilium/cilium-cli/issues/57 that was since fixed.

PR for testing workflow changes: #376

### CODE REVIEW

**Comment by nbusseneau** [comment]
EKS test successful, so at least the PR itself is sound.

Go test https://github.com/cilium/cilium-cli/actions/runs/950721365 failed with:
```
 go test -timeout=5s -race -cover $(go list ./...)
?   	github.com/cilium/cilium-cli/clustermesh	[no test files]
?   	github.com/cilium/cilium-cli/cmd/cilium	[no test files]
?   	github.com/cilium/cilium-cli/config	[no test files]
?   	github.com/cilium/cilium-cli/connectivity	[no test files]
?   	github.com/cilium/cilium-cli/connectivity/check	[no test files]
?   	github.com/cilium/cilium-cli/connectivity/filters	[no test files]
?   	github.com/cilium/cilium-cli/connectivity/tests	[no test files]
?   	github.com/cilium/cilium-cli/defaults	[no test files]
?   	github.com/cilium/cilium-cli/hubble	[no test files]
# github.com/cilium/cilium-cli/internal/utils [github.com/cilium/cilium-cli/internal/utils.test]
internal/utils/exec_test.go:20:2: check redeclared as imported package name
	previous declaration at internal/utils/utils.go:27
ok  	github.com/cilium/cilium-cli/install	0.308s	coverage: 1.4% of statements
?   	github.com/cilium/cilium-cli/internal/certs	[no test files]
?   	github.com/cilium/cilium-cli/internal/cli/cmd	[no test files]
?   	github.com/cilium/cilium-cli/internal/k8s	[no test files]
FAIL	github.com/cilium/cilium-cli/internal/utils [build failed]
ok  	github.com/cilium/cilium-cli/status	0.268s	coverage: 71.3% of statements
?   	github.com/cilium/cilium-cli/sysdump	[no test files]
FAIL
make: *** [Makefile:69: test] Error 2
Error: Process completed with exit code 2.
```

GKE test https://github.com/cilium/cilium-cli/actions/runs/950721302 failed with #344:
```
  [-] Scenario [allow-all/pod-to-remote-nodeport]
  [.] Action [allow-all/pod-to-remote-nodeport/curl-0: cilium-test/client-7b7bf54b85-fgwd9 (10.0.1.73) -> cilium-test/echo-other-node (echo-other-node:8080)]
  ❌ command "curl -w %***local_ip***:%***local_port*** -> %***remote_ip***:%***remote_port*** = %***response_code*** --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.168.0.49:31623" failed: command terminated with exit code 7

[...]

   ❌ Flow validation failed for pod cilium-test/client-7b7bf54b85-fgwd9: 1 failures (first: -1, last: -1, matched: 0)
  
  📄 Flow logs for pod cilium-test/client-7b7bf54b85-fgwd9:
  ❓ [0] Jun 18 18:23:24.847: cilium-test/client-7b7bf54b85-fgwd9:44832 -> 10.168.0.49:31623 from-endpoint FORWARDED (TCP Flags: SYN)
  ❓ [1] Jun 18 18:23:24.847: cilium-test/client-7b7bf54b85-fgwd9:44832 -> 10.168.0.49:31623 all FORWARDED (TCP Flags: SYN)
  ❓ [2] Jun 18 18:23:24.847: cilium-test/client-7b7bf54b85-fgwd9:44832 -> 10.168.0.49:31623 to-stack FORWARDED (TCP Flags: SYN)
  ❓ [3] Jun 18 18:23:24.848: 10.168.0.49 -> cilium-test/client-7b7bf54b85-fgwd9 from-stack FORWARDED (ICMPv4 DestinationUnreachable(Port))
  ❓ [4] Jun 18 18:23:24.848: 10.168.0.49 -> cilium-test/client-7b7bf54b85-fgwd9 to-endpoint FORWARDED (ICMPv4 DestinationUnreachable(Port))

[...]

📋 Test Report
❌ 1/9 tests failed (1/81 actions), 0 warnings, 0 tests skipped, 0 scenarios skipped:
Test [allow-all]:
  ❌ allow-all/pod-to-remote-nodeport/curl-0: cilium-test/client2-666976c95b-jxml8 (10.0.0.27) -> cilium-test/echo-other-node (echo-other-node:8080)
error: cannot exec into a container in a completed pod; current phase is Failed
```

**Comment by nbusseneau** [comment]
We'll have to make a test PR switching from `pull_request_target` to `pull_request` for testing if the EKS workflow works, I'll do that when I'm back.

**Comment by tklauser** [comment]
This will also need a rebase to fix the unit test build failure caused by the `check` name redeclaration (https://github.com/cilium/cilium-cli/pull/339/checks?check_run_id=2860841188). This was fixed in commit 2f9ac9b2e2cb8d3cd0246c56c3ca38035d04f2a3

**Comment by nbusseneau** [comment]
EKS test from test PR successful: https://github.com/cilium/cilium-cli/actions/runs/979777872

**Review by tklauser — APPROVED** [review]

**Pull request merged**
