### PR TITLE
Fix build on 32-bit platforms

### PR DESCRIPTION
**Pull request by tklauser**
The build for 32-bit platforms (e.g. `linux/arm`) currently fails with:
```
connectivity/check/action.go:389:11: constant 4294967295 overflows int
```

Fix this and extend the Go GitHub action to cross-build all supported platforms, i.e. the ones supported by `make local-release` and provided as binary releases on this repo.

### CODE REVIEW

**Comment by michi-covalent** [comment]
```
Errors:           hubble-relay       hubble-relay    1 pods of DaemonSet hubble-relay are not ready
```
😢

**Review by michi-covalent — APPROVED** [review]
looking into the aks failure

**Comment by michi-covalent** [comment]
relay failing to connect to hubble 👀 
```
2021-06-17T10:40:10.194546685Z level=warning msg="Failed to create gRPC client" address="10.240.0.4:4244" error="context deadline exceeded" hubble-tls=true next-try-in=10s peer=cilium-cilium-cli-946050162/aks-nodepool1-17851042-vmss000000 subsys=hubble-relay
2021-06-17T10:40:10.194575985Z level=warning msg="Failed to create gRPC client" address="10.240.0.35:4244" error="context deadline exceeded" hubble-tls=true next-try-in=10s peer=cilium-cilium-cli-946050162/aks-nodepool1-17851042-vmss000001 subsys=hubble-relay
2021-06-17T10:40:34.511083259Z level=info msg="Stopping server..." subsys=hubble-relay
```

**Comment by michi-covalent** [comment]
... and should we be concerned about these error messages:
```
cilium-44q6d-cilium-agent-20210617-104514.log:2021-06-17T10:30:12.750287516Z level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
cilium-7bf5f-cilium-agent-20210617-104515.log:2021-06-17T10:30:45.305407878Z level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
```

**Review by nbusseneau — APPROVED** [review]
Code change LGTM. Wondering if the failure is a flake, I've seen it in other PRs in the past, though seldomly.

**Comment by michi-covalent** [comment]
@nbusseneau https://github.com/cilium/cilium-cli/pull/335 should help with this specific failure where relay gets into crash loop backoff

**Comment by nbusseneau** [comment]
I think yes!

**Comment by michi-covalent** [comment]
ok this is a known flake, filed https://github.com/cilium/cilium-cli/issues/342 to track. will merge this one.

**Pull request merged**
