### PR TITLE
install: gofmt

### PR DESCRIPTION
**Pull request by tklauser**
Commit 6bbb25c3aa67 ("azure: refactor subscription parameter") wasn't
properly `gofmt`ed.

### CODE REVIEW

**Comment by rolinh** [comment]
What about enabling `gofmt` in `golangci-lint` config so that unformatted code is caught by the linter?

**Comment by tklauser** [comment]
> What about enabling `gofmt` in `golangci-lint` config so that unformatted code is caught by the linter?

I think it's already run as part of the `goimports` check. It was actually caught and the GH action failed, but #227 was merged nevertheless :cry:

**Comment by nbusseneau** [comment]
> I think it's already run as part of the `goimports` check. It was actually caught and the GH action failed, but #227 was merged nevertheless cry
All checks were green 🤔 https://github.com/cilium/cilium-cli/pull/227/checks
Are we missing something?

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
> > I think it's already run as part of the `goimports` check. It was actually caught and the GH action failed, but #227 was merged nevertheless cry
> 
> All checks were green thinking https://github.com/cilium/cilium-cli/pull/227/checks
> Are we missing something?

From the log output it looks like #227 was still using the old non-golanglint-ci checks and for some reason `make gofmt` didn't actually run anything. After it was rebased and merged, the golanglint-ci based checks started kicking in and failed.

**Review by michi-covalent — APPROVED** [review]

**Comment by nebril** [comment]
Hit https://github.com/cilium/cilium-cli/issues/224 , merging

**Review by nebril — APPROVED** [review]

**Pull request merged**
