### PR TITLE
Version tag handling fixes

### PR DESCRIPTION
**Pull request by jrajahalme**
Set image tag when overriding images, as otherwise "latest" will be used
by k8s.

Use operator.useDigest instead of operator.digest, which does not exist.

Only set image.tag if not overriding images.

Pass SHAs and "latest" through --version validation, so that a SHA can be
used as --version as intended.

Detect running Cilium version as "latest" if image has no tag, rather
than erroring out. This may happen if image tag is not specified for a
pod.

### CODE REVIEW

**Review by sayboras — COMMENTED** [review]
The changes looks very similar to me, was it part of this https://github.com/cilium/cilium-cli/pull/798/files ?

**Comment by aanm** [comment]
Don't forget to run the CI against this PR by removing these lines on all GH actions: https://github.com/cilium/cilium-cli/blob/master/.github/workflows/gke.yaml#L17

**Comment by jrajahalme** [comment]
> https://github.com/cilium/cilium-cli/pull/798/files

Yes, but I made #798 a draft, it may not be needed. This PR is factoring out the command line fixes from that PR.

**Comment by jrajahalme** [comment]
> Don't forget to run the CI against this PR by removing these lines on all GH actions: https://github.com/cilium/cilium-cli/blob/master/.github/workflows/gke.yaml#L17

Added the `DO NOT MERGE` commit :-)

**Comment by jrajahalme** [comment]
@aanm CI passed with the DO NOT MERGE commit, removing it now.

**Comment by jrajahalme** [comment]
@aanm as part of fixing the unit test for the version parsing I made the regexp to accept bare SHA (no colons) only when it is 40 hex digits, as is the case with git. This allowed an existing test of `ddd` to fail as expected (it's only 3 hex digits).

**Review by aanm — APPROVED** [review]
Thanks @jrajahalme

**Review by tklauser — APPROVED** [review]

**Pull request merged**
