### PR TITLE
Prepare for v0.16.21 release

### PR DESCRIPTION
**Pull request by tklauser**
Testing CI but wait for Cilium v1.17.0-pre.3 to be released before reviewing/merging this.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
very nice

**Comment by tklauser** [comment]
Most (all?) of the test failures are due to warning logs in the Cilium and Hubble UI logs. These get treated as errors since https://github.com/cilium/cilium/pull/35723. To allow skipping this check temporarily (and not block the release for too long to wait for all fixes to be done and merged), I've added a flag to specify log levels to check: https://github.com/cilium/cilium/pull/36231

**Comment by Foxboron** [comment]
Please consider this issue before doing a new release.

https://github.com/cilium/cilium-cli/issues/2870

**Comment by michi-covalent** [comment]
thanks for the heads up @Foxboron i think i'm the one for suggested curling stable.txt from cilium/cilium repo, and i acknowledge that it's not great for downstream package managers to have releases that are not reproducible.

@tklauser what do you think about getting the latest release from the vendored cilium/chart repo? that way the default stable cilium version won't move around. something like:

```
% ls vendor/github.com/cilium/charts/ | grep -E "cilium-[0-9]+\.[0-9]+\.[0-9]+\.tgz" | sort -V | tail -n 1 | sed -E 's/cilium-([0-9]+\.[0-9]+\.[0-9]+).tgz/\1/'
1.16.3
```

**Review by michi-covalent — APPROVED** [review]
lgtm i'll try to update https://github.com/cilium/cilium-cli/pull/2874 today 🙏 

edit: ah never mind i need to make change in cilium/cilium repo. don't wait for https://github.com/cilium/cilium-cli/pull/2874

**Review by brlbil — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]

**Comment by tklauser** [comment]
Currently blocked on https://github.com/cilium/cilium/pull/36358 getting merged to cilium/cilium. Once it is, I'll update this PR.

**Pull request merged**
