### PR TITLE
Update default Cilium version to 1.13.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Comment by viktor-kurchenko** [comment]
There are few version references in README, should they be updated too?

**Comment by tklauser** [comment]
> There are few version references in README, should they be updated too?

Good point, thanks. Added a separate commit updating `README.md` with latest stable Cilium releases.

**Comment by tklauser** [comment]
Workflows passed with test commit (except for multicluster which flaked on cluster provisioning). Removing test commit.

**Review by squeed — APPROVED** [review]

**Pull request merged**
