### PR TITLE
Update kind and helm/kind-action

### PR DESCRIPTION
**Pull request by tklauser**
Update kind to v0.11.1 and the helm/kind-action to v1.2.0

### CODE REVIEW

**Comment by tklauser** [comment]
This seems to fix the kind GH action job failures we've been seeing on `master` recently. No idea why though :shrug:

**Review by michi-covalent — APPROVED** [review]
mysterious but ship it

**Review by nbusseneau — APPROVED** [review]
Don't like not knowing why it started to fail but :shipit:

**Comment by tklauser** [comment]
Seems like other people have been hitting the same mystery: https://github.com/helm/kind-action/issues/42

**Review by christarazi — APPROVED** [review]

**Pull request merged**
