### PR TITLE
workflows: refactor EKS workflows

### PR DESCRIPTION
**Pull request by nbusseneau**
Following merge of #400, we broke #391.

This PR fixes the issue by refactoring both EKS workflows to be consistent with other workflows, now that we are creating a cluster with nodes available right away just like on other platforms, and thus do not need to split the `install`/`test` steps anymore.

### CODE REVIEW

**Comment by nbusseneau** [comment]
- EKS was successful: https://github.com/cilium/cilium-cli/actions/runs/1045185935
- EKS in tunnel mode hit #367: https://github.com/cilium/cilium-cli/actions/runs/1045185944
```
2021-07-19T12:57:29.635847099Z [=] Test [to-fqdns]
2021-07-19T12:57:29.980356968Z   🐛 Pod kube-system/cilium-p2wwn's current policy revision 9
2021-07-19T12:57:29.980381459Z   🐛 Pod kube-system/cilium-m4tfp's current policy revision 9
2021-07-19T12:57:29.980384681Z   ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-to-fqdns-cilium-io' to namespace 'cilium-test'..
2021-07-19T12:57:30.011214701Z   🐛 Policy difference detected, waiting for Cilium agents to increment policy revisions..
2021-07-19T12:57:31.335559178Z   🐛 Pod cilium-cilium-cli-1045185944-tunnel.us-east-2.eksctl.io/kube-system/cilium-m4tfp revision > 9
2021-07-19T12:57:31.497517029Z   🐛 Pod cilium-cilium-cli-1045185944-tunnel.us-east-2.eksctl.io/kube-system/cilium-p2wwn revision > 9
2021-07-19T12:57:31.497572616Z   🐛 📜 Successfully applied 1 CiliumNetworkPolicies
2021-07-19T12:57:31.497576432Z   [-] Scenario [to-fqdns/pod-to-world]
2021-07-19T12:57:31.497579192Z   🐛 Expecting egress drops for Action https-to-cilium-io: Drop-DNS
2021-07-19T12:57:31.497582325Z   [.] Action [to-fqdns/pod-to-world/https-to-cilium-io: cilium-test/client2-666976c95b-mrztf (10.0.1.149) -> cilium-io-https (cilium.io:443)]
2021-07-19T12:57:31.504289105Z   🐛 Connected to Hubble node(s) [cilium-cilium-cli-1045185944-tunnel/ip-192-168-128-192.us-east-2.compute.internal cilium-cilium-cli-1045185944-tunnel/ip-192-168-106-246.us-east-2.compute.internal]
2021-07-19T12:57:31.504323895Z   📄 Following flows...
2021-07-19T12:57:31.504327927Z   🐛 Executing command [curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null https://cilium.io:443]
2021-07-19T12:57:36.656833721Z   🐛 curl stderr: curl: (28) Resolving timed out after 5000 milliseconds
2021-07-19T12:57:36.656875595Z 
2021-07-19T12:57:36.656896436Z   🐛 command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null https://cilium.io:443" failed as expected: command terminated with exit code 28
2021-07-19T12:57:36.656902388Z   📄 Validating flows for peer cilium-test/client2-666976c95b-mrztf
2021-07-19T12:57:37.157269615Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:37.157314417Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:37.657904424Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:37.658001933Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:38.157579882Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:38.157617110Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:38.656959754Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:38.656992171Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:39.157651746Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:39.157747922Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:39.657166222Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:39.657215015Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:40.157770216Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:40.157802903Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:40.657581260Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:40.657612969Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:41.157101476Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:41.157138521Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:41.657773639Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:41.657816567Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:42.157936425Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:42.157969796Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:42.657625581Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:42.657665875Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:43.157423134Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:43.157537908Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:43.657868476Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:43.657900524Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:44.157664279Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:44.157706249Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:44.657227732Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:44.657268947Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:45.157856057Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:45.157890440Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:45.657579401Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:45.657871204Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:46.157853973Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:46.157888199Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:46.657912492Z   🐛 Validating 26 flows against 2 requirements
2021-07-19T12:57:46.658143148Z   ℹ️  SYN and(ip(src=10.0.1.149),tcp(dstPort=443),tcpflags(syn)) not found
2021-07-19T12:57:46.658153501Z   ❌ Aborting flow matching: context deadline exceeded
2021-07-19T12:57:46.658157444Z   ❌ Flow validation failed for peer cilium-test/client2-666976c95b-mrztf: 0 failures (first: -1, last: -1, matched: 0)
2021-07-19T12:57:46.658160857Z   
2021-07-19T12:57:46.658164195Z   📄 Flow logs for peer cilium-test/client2-666976c95b-mrztf:
2021-07-19T12:57:46.658167306Z   ❓ [0] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658194984Z   ❓ [1] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 L3-L4 FORWARDED (UDP)
2021-07-19T12:57:46.658199426Z   ❓ [2] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658203087Z   ❓ [3] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658206587Z   ❓ [4] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658232982Z   ❓ [5] Jul 19 12:57:31.611: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 dns-request FORWARDED (DNS Query cilium.io.cilium-test.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658247054Z   ❓ [6] Jul 19 12:57:31.611: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 dns-request FORWARDED (DNS Query cilium.io.cilium-test.svc.cluster.local. A)
2021-07-19T12:57:46.658251027Z   ❓ [7] Jul 19 12:57:31.612: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy cilium.io.cilium-test.svc.cluster.local. AAAA))
2021-07-19T12:57:46.658254959Z   ❓ [8] Jul 19 12:57:31.612: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy cilium.io.cilium-test.svc.cluster.local. A))
2021-07-19T12:57:46.658278359Z   ❓ [9] Jul 19 12:57:31.612: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658282576Z   ❓ [10] Jul 19 12:57:31.612: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. A)
2021-07-19T12:57:46.658286356Z   ❓ [11] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658289924Z   ❓ [12] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 L3-L4 FORWARDED (UDP)
2021-07-19T12:57:46.658294079Z   ❓ [13] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658297508Z   ❓ [14] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658320006Z   ❓ [15] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658324437Z   ❓ [16] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 from-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658328029Z   ❓ [17] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 to-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658331552Z   ❓ [18] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 from-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658353141Z   ❓ [19] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 to-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658357428Z   ❓ [20] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658360627Z   ❓ [21] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658364410Z   ❓ [22] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658370837Z   ❓ [23] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658395610Z   ❓ [24] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658399936Z   ❓ [25] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. A)
2021-07-19T12:57:46.658403598Z   
2021-07-19T12:57:46.658406443Z   📄 Flow logs for peer cilium-io-https:
2021-07-19T12:57:46.658409847Z   ❓ [0] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658413577Z   ❓ [1] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 L3-L4 FORWARDED (UDP)
2021-07-19T12:57:46.658436641Z   ❓ [2] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658441057Z   ❓ [3] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658444584Z   ❓ [4] Jul 19 12:57:31.610: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658448466Z   ❓ [5] Jul 19 12:57:31.611: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 dns-request FORWARDED (DNS Query cilium.io.cilium-test.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658452384Z   ❓ [6] Jul 19 12:57:31.611: cilium-test/client2-666976c95b-mrztf:59493 -> kube-system/coredns-5c778788f4-pcn2h:53 dns-request FORWARDED (DNS Query cilium.io.cilium-test.svc.cluster.local. A)
2021-07-19T12:57:46.658482079Z   ❓ [7] Jul 19 12:57:31.612: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy cilium.io.cilium-test.svc.cluster.local. AAAA))
2021-07-19T12:57:46.658487056Z   ❓ [8] Jul 19 12:57:31.612: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy cilium.io.cilium-test.svc.cluster.local. A))
2021-07-19T12:57:46.658491373Z   ❓ [9] Jul 19 12:57:31.612: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658495269Z   ❓ [10] Jul 19 12:57:31.612: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. A)
2021-07-19T12:57:46.658499310Z   ❓ [11] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658502917Z   ❓ [12] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 L3-L4 FORWARDED (UDP)
2021-07-19T12:57:46.658535721Z   ❓ [13] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658540261Z   ❓ [14] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658544314Z   ❓ [15] Jul 19 12:57:31.613: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658547896Z   ❓ [16] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 from-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658642977Z   ❓ [17] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 to-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658649042Z   ❓ [18] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 from-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658652395Z   ❓ [19] Jul 19 12:57:31.613: kube-system/coredns-5c778788f4-pcn2h:53 -> cilium-test/client2-666976c95b-mrztf:59493 to-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658655727Z   ❓ [20] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658688642Z   ❓ [21] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658692406Z   ❓ [22] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
2021-07-19T12:57:46.658695560Z   ❓ [23] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 to-proxy FORWARDED (UDP)
2021-07-19T12:57:46.658698711Z   ❓ [24] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. AAAA)
2021-07-19T12:57:46.658702125Z   ❓ [25] Jul 19 12:57:34.115: cilium-test/client2-666976c95b-mrztf:60730 -> kube-system/coredns-5c778788f4-nstrx:53 dns-request FORWARDED (DNS Query cilium.io.svc.cluster.local. A)
```
- Multicluster hit #361: https://github.com/cilium/cilium-cli/actions/runs/1045185846
```
2021-07-19T12:45:12.097174459Z Error: Connectivity test failed: timeout reached waiting for pod IDs in ipcache of Cilium pod kube-system/cilium-pkl65
2021-07-19T12:45:12.097227036Z 🐛 Couldn't find client Pod cilium-test/client-7b7bf54b85-fnfjr in ipcache, retrying...
```

**Comment by nbusseneau** [comment]
Since this is an urgent PR for fixing regressions in `master`, and both EKS runs demonstrated the issue was fixed, I am removing the temporary test commit and marking as `ready-to-merge` despite the flakes hit.

**Review by tklauser — APPROVED** [review]
Thanks

**Comment by joestringer** [comment]
@aanm has more context than me on the changes that are mentioned in the PR description here, and also implications on github workflows so I've pulled him in on review.

**Review by aanm — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
ok let's ship it

**Pull request merged**
