### PR TITLE
fix: update ldflags for local-release

### PR DESCRIPTION
**Pull request by chenrui333**
followup #2362

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @michi-covalen @nathanjsweet

**Review by michi-covalent — APPROVED** [review]
oh good catch. thanks for the fix!

**Comment by senges** [comment]
Any chance we could release a patch version as `cilium version` won't work on github releases ?

 Thanks for the fix !

**Comment by michi-covalent** [comment]
yeah we are doing patch releases for cilium/cilium this week. we'll cut a cilium-cli release after that 🚀🙏

**Comment by senges** [comment]
Alright thanks :pray:

**Pull request merged**
