### PR TITLE
test: Implement `--flow-validation=disabled`

### PR DESCRIPTION
**Pull request by pchaigno**
Fixes: https://github.com/cilium/cilium-cli/issues/293.

### CODE REVIEW

**Comment by michi-covalent** [comment]
cc @jrajahalme looking at the log timestamp, not sure if it's waiting for 5 seconds before retrying 🤔 
```
2021-06-11T17:08:45.3345961Z   [.] Action [dns-only/pod-to-world/https-to-google: cilium-test/client-8655c47fd7-8d9v2 (10.244.1.45) -> google-https (google.com:443)]
2021-06-11T17:08:45.3347497Z   📄 Matching flows for pod cilium-test/client-8655c47fd7-8d9v2
2021-06-11T17:08:45.3349225Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3350216Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3351136Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3352048Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3354118Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3355226Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3357111Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3359387Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3361368Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3363223Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3364658Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3365801Z   ⌛ Waiting (5s) for flows: Required flows not found yet
2021-06-11T17:08:45.3367448Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3368392Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3369887Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3370843Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3371767Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3372977Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3374715Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3376599Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3377982Z   ℹ️  SYN and(ip(src=10.244.1.45),tcp(dstPort=443),tcpflags(syn)) not found
2021-06-11T17:08:45.3378955Z   ✅ DNS request found at 0
2021-06-11T17:08:45.3379650Z   ✅ DNS response found at 5
2021-06-11T17:08:45.3381026Z   ❌ Flow validation failed for pod cilium-test/client-8655c47fd7-8d9v2: 1 failures (first: 0, last: 5, matched: 2)
```

**Comment by jrajahalme** [comment]
> cc @jrajahalme looking at the log timestamp, not sure if it's waiting for 5 seconds before retrying 🤔

That 5s is the time from the validation start to the warning message. The timestamps you see on the left are all bunched up because the logs are actually printed out all at once after the first failure. We should do better job outputting timestamps in the logs themselves so that we would not need to rely on `kubectl logs --timestamps`.

**Comment by jrajahalme** [comment]
@michi-covalent You should rebase as #301 was merged recently. That potentially fixes this issue as it seems retries of getting the flows from Hubble did not really happen.

**Comment by jrajahalme** [comment]
Actually, it looks like it is refetching the logs from hubble for about 10 seconds, every 500ms. If that did not happen we would not see the attempt to find the SYN ~20 times.

**Review by michi-covalent — APPROVED** [review]

**Comment by pchaigno** [comment]
I've retriggered the two failing tests given this is blocking the release.

**Review by nbusseneau — APPROVED** [review]
Good catch 🚀

**Review by christarazi — APPROVED** [review]

**Comment by michi-covalent** [comment]
>   ❌ to-fqdns/pod-to-world/http-to-google: cilium-test/client-8655c47fd7-4kzv7 (10.240.0.63) -> google-http (google.com:80)

we are working on improving the flow validation stability in https://github.com/cilium/cilium-cli/pull/319. i'm merging this.

**Pull request merged**
