### PR TITLE
install: add support for AWS with CNI chaining

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by pchaigno — COMMENTED** [review]
Thanks!

How is this used? `./cilium install --config cni-chaining-mode=aws-cni`? If that's it, should we document it somewhere?

**Comment by aanm** [comment]
> Thanks!
> 
> How is this used? `./cilium install --config cni-chaining-mode=aws-cni`? If that's it, should we document it somewhere?

@pchaigno how is it currently done in our docs?

**Comment by pchaigno** [comment]
Our cilium/cilium docs currently use Helm for the AWS-CNI getting started guide and the CLI doesn't really have any other docs than `--help` AFAIK.

**Review by twpayne — APPROVED** [review]
Rubber stamp LGTM.

**Review by pchaigno — APPROVED** [review]
Discussed offline. This can be enabled with `--helm-set cni.chainingMode=aws-cni` as other Helm flags, so we probably don't need specific documentation here and should just document in cilium/cilium for the AWS-CNI chaining guide.

**Pull request merged**
